// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUPakmqh9riG0pqY2FoMxj1lLscR9kf8A',
    appId: '1:857953782811:web:56947016778063084f7cbe',
    messagingSenderId: '857953782811',
    projectId: 'fooddash-d48ee',
    authDomain: 'fooddash-d48ee.firebaseapp.com',
    storageBucket: 'fooddash-d48ee.firebasestorage.app',
    measurementId: 'G-6FWGY6L0MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvjCpPeIASmE_qpwVCZOU2HEk6p7I-MY',
    appId: '1:857953782811:android:622bbec5b52cb1814f7cbe',
    messagingSenderId: '857953782811',
    projectId: 'fooddash-d48ee',
    storageBucket: 'fooddash-d48ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGBqFdxKWzT0Jy8pzkpgXtb49QemmVlGM',
    appId: '1:857953782811:ios:1da924b05c2057a24f7cbe',
    messagingSenderId: '857953782811',
    projectId: 'fooddash-d48ee',
    storageBucket: 'fooddash-d48ee.firebasestorage.app',
    iosBundleId: 'com.example.fooduu',
  );

}